# Generated by Django 4.1 on 2025-09-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(max_length=50, unique=True, verbose_name='資産番号')),
                ('name', models.CharField(max_length=200, verbose_name='品名')),
                ('asset_type', models.CharField(choices=[('pc', 'パソコン'), ('laptop', 'ノートPC'), ('tablet', 'タブレット'), ('printer', 'プリンター'), ('monitor', 'モニター'), ('phone', '電話機'), ('medical', '医療機器'), ('furniture', '家具'), ('other', 'その他')], max_length=20, verbose_name='種別')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='メーカー')),
                ('model_number', models.CharField(blank=True, max_length=100, verbose_name='型番')),
                ('purchase_date', models.DateField(verbose_name='購入日')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='購入価格')),
                ('status', models.CharField(choices=[('available', '利用可能'), ('in_use', '利用中'), ('maintenance', '修理中'), ('retired', '廃棄')], default='available', max_length=20, verbose_name='状態')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='設置場所')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'リース品',
                'verbose_name_plural': 'リース品一覧',
                'ordering': ['asset_number'],
            },
        ),
    ]
