# Generated by Django 4.1 on 2025-09-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asset',
            table='monolis_asset',
        ),
    ]
