# Generated by Django 4.1 on 2025-09-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asset',
            table='asset',
        ),
    ]
